---
# role: ansible-role-packer-provision
# file: tasks/swap.yml

- name: "Role packer_provision | Disable all swap files"
  ansible.builtin.command: "swapoff -a"
  changed_when: false
  when: ansible_swaptotal_mb > 0

- name: "Role packer_provision | Delete swap file"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/swap.img"
    - "/swapfile"
    - "/var/swapfile"

- name: "Role packer_provision | Remove swap entry from fstab"
  ansible.posix.mount:
    path: "{{ item.mount }}"
    state: absent
  loop: "{{ ansible_mounts }}"
  when: item.fstype == "swap"

- name: "Role packer_provision | Set vm.swappiness to 1"
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '1'
    reload: true
    state: present
    sysctl_set: true
    sysctl_file: "/etc/sysctl.d/99-swappiness.conf"
