---
# role: ansible-role-pp
# file: molecule/virtualbox/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: pp-alpine312
    box: "generic/alpine312"
    cpus: 2
    memory: 1024
  - name: pp-arch
    box: "archlinux/archlinux"
    cpus: 2
    memory: 1024
  - name: pp-centos8
    box: "centos/8"
    cpus: 2
    memory: 1024
  - name: pp-debian11
    box: "debian/bullseye64"
    cpus: 2
    memory: 1024
  - name: pp-fedora33
    box: "fedora/33-cloud-base"
    cpus: 2
    memory: 1024
  - name: pp-ubuntu2004
    box: "ubuntu/focal64"
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        packer_builder_type: "virtualbox-iso"
verifier:
  name: ansible
